### ISSUE TITLE
Can't use the Annotation view feature when non-default state capture is enabled

### ISSUE THREAD

**Issue by sdumetz** [Smithsonian/dpo-voyager#258]
I get the following error when I try to restore the view :
```
Uncaught TypeError: Cannot read properties of null (reading '0')
    at CVSnapshots.setValues (CTweenMachine.ts:412:55)
    at CVSnapshots.tick (CTweenMachine.ts:217:18)
    at Graph.tick (Graph.ts:250:49)
    at CVDocument.tick (CGraph.ts:102:33)
    at Graph.tick (Graph.ts:256:50)
    at CPulse.pulse (CPulse.ts:121:47)
    at CPulse.onAnimationFrame (CPulse.ts:133:14)
```

Apparently linked to how the state array is only sparsely filled when doing an annotation state capture.

**Comment by gjcope** [comment]
Have you done a submodule update?

**Comment by gjcope** [comment]
If so, please provide steps to reproduce. Thanks!

**Comment by sdumetz** [comment]
Oh, my bad. I forgot to set `submodule.recurse` in the git config and didn't double-check after I pulled the update...

Yet another reason not to like submodules :)

Sorry for the inconvenience.
